version: 2

models:
  - name: clean_weather
    description: "Cleaned and deduplicated weather data"
    columns:
      - name: city
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: ingested_at
        tests:
         - not_null