version: 2

models:
  - name: stg_timesheets
    columns:

      - name: ingested_at
        tests:
          - not_null
      
      - name: category
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['full', 'missing', 'saved']