select
    "Organization"     as organization,
    "Manager"          as manager_name,
    "Employee ID"      as employee_id,
    "Employee Name"    as employee_name,
    "category"         as category,
    "ingested_at"      as ingested_at,
    "Project Number"   as project_number,
    "Task Number"      as task_number,
    "Org Level 4 Name" as org_level_4_name,
    "Grand Total"      as grand_total,
    "year" as year,
    "5-Jan"   as week_05_jan,
    "12-Jan"  as week_12_jan,
    "19-Jan"  as week_19_jan,
    "26-Jan"  as week_26_jan,
    "2-Feb"   as week_02_feb,
    "9-Feb"   as week_09_feb,
    "16-Feb"  as week_16_feb,
    "23-Feb"  as week_23_feb,
    "2-Mar"   as week_02_mar,
    "9-Mar"   as week_09_mar,
    "16-Mar"  as week_16_mar,
    "23-Mar"  as week_23_mar,
    "30-Mar"  as week_30_mar,
    "6-Apr"   as week_06_apr,
    "13-Apr"  as week_13_apr,
    "20-Apr"  as week_20_apr,
    "27-Apr"  as week_27_apr,
    "4-May"   as week_04_may,
    "11-May"  as week_11_may,
    "18-May"  as week_18_may,
    "25-May"  as week_25_may,
    "1-Jun"   as week_01_jun,
    "8-Jun"   as week_08_jun,
    "15-Jun"  as week_15_jun,
    "22-Jun"  as week_22_jun,
    "29-Jun"  as week_29_jun,
    "6-Jul"   as week_06_jul,
    "13-Jul"  as week_13_jul,
    "20-Jul"  as week_20_jul,
    "27-Jul"  as week_27_jul,
    "3-Aug"   as week_03_aug,
    "10-Aug"  as week_10_aug,
    "17-Aug"  as week_17_aug,
    "24-Aug"  as week_24_aug,
    "31-Aug"  as week_31_aug,
    "7-Sep"   as week_07_sep,
    "14-Sep"  as week_14_sep,
    "21-Sep"  as week_21_sep,
    "28-Sep"  as week_28_sep,
    "5-Oct"   as week_05_oct,
    "12-Oct"  as week_12_oct,
    "19-Oct"  as week_19_oct,
    "26-Oct"  as week_26_oct,
    "2-Nov"   as week_02_nov,
    "9-Nov"   as week_09_nov,
    "16-Nov"  as week_16_nov,
    "23-Nov"  as week_23_nov,
    "30-Nov"  as week_30_nov,
    "7-Dec"   as week_07_dec,
    "14-Dec"  as week_14_dec,
    "21-Dec"  as week_21_dec,
    "28-Dec"  as week_28_dec
from {{ source('bronze', 'timesheets') }}